/**
 * GENERATED by scripts/import-exercise-library.mjs — do not edit by hand.
 *
 * The 287 exercises the app did not already have, from the Workout Guide
 * catalogue. The original 15 stay in data.ts with their own ids:
 *
 *  ex1 -> bench-press
 *  ex2 -> dumbbell-fly
 *  ex3 -> push-up
 *  ex4 -> pull-up
 *  ex5 -> barbell-row
 *  ex6 -> deadlift
 *  ex7 -> squat
 *  ex8 -> leg-press
 *  ex9 -> forward-lunge
 *  ex10 -> overhead-press
 *  ex11 -> lateral-raise
 *  ex12 -> bicep-curl
 *  ex13 -> bench-dip
 *  ex14 -> plank
 *  ex15 -> crunch
 */

import type { Exercise } from './types';

export const LIBRARY_EXERCISES: Exercise[] = [
  {
    "id": "lib-incline-bench-press",
    "name": "inclineBenchPress",
    "bodyPart": "Chest",
    "description": "inclineBenchPressDescription",
    "emoji": "🏋️",
    "tracking": "weight",
    "illustration": "incline-bench-press"
  },
  {
    "id": "lib-incline-dumbbell-press",
    "name": "inclineDumbbellPress",
    "bodyPart": "Chest",
    "description": "inclineDumbbellPressDescription",
    "emoji": "🏋️",
    "tracking": "weight",
    "illustration": "incline-dumbbell-press"
  },
  {
    "id": "lib-dumbbell-bench-press",
    "name": "dumbbellBenchPress",
    "bodyPart": "Chest",
    "description": "dumbbellBenchPressDescription",
    "emoji": "🏋️",
    "tracking": "weight",
    "illustration": "dumbbell-bench-press"
  },
  {
    "id": "lib-decline-bench-press",
    "name": "declineBenchPress",
    "bodyPart": "Chest",
    "description": "declineBenchPressDescription",
    "emoji": "🏋️",
    "tracking": "weight",
    "illustration": "decline-bench-press"
  },
  {
    "id": "lib-machine-chest-press",
    "name": "machineChestPress",
    "bodyPart": "Chest",
    "description": "machineChestPressDescription",
    "emoji": "🏋️",
    "tracking": "weight",
    "illustration": "machine-chest-press"
  },
  {
    "id": "lib-pec-deck",
    "name": "pecDeck",
    "bodyPart": "Chest",
    "description": "pecDeckDescription",
    "emoji": "🏋️",
    "tracking": "weight",
    "illustration": "pec-deck"
  },
  {
    "id": "lib-cable-fly",
    "name": "cableFly",
    "bodyPart": "Chest",
    "description": "cableFlyDescription",
    "emoji": "🏋️",
    "tracking": "weight",
    "illustration": "cable-fly"
  },
  {
    "id": "lib-weighted-push-up",
    "name": "weightedPushUp",
    "bodyPart": "Chest",
    "description": "weightedPushUpDescription",
    "emoji": "🏋️",
    "tracking": "weight",
    "illustration": "weighted-push-up"
  },
  {
    "id": "lib-seated-dumbbell-press",
    "name": "seatedDumbbellPress",
    "bodyPart": "Shoulders",
    "description": "seatedDumbbellPressDescription",
    "emoji": "🤷",
    "tracking": "weight",
    "illustration": "seated-dumbbell-press"
  },
  {
    "id": "lib-arnold-press",
    "name": "arnoldPress",
    "bodyPart": "Shoulders",
    "description": "arnoldPressDescription",
    "emoji": "🤷",
    "tracking": "weight",
    "illustration": "arnold-press"
  },
  {
    "id": "lib-cable-lateral-raise",
    "name": "cableLateralRaise",
    "bodyPart": "Shoulders",
    "description": "cableLateralRaiseDescription",
    "emoji": "🤷",
    "tracking": "weight",
    "illustration": "cable-lateral-raise"
  },
  {
    "id": "lib-front-raise",
    "name": "frontRaise",
    "bodyPart": "Shoulders",
    "description": "frontRaiseDescription",
    "emoji": "🤷",
    "tracking": "weight",
    "illustration": "front-raise"
  },
  {
    "id": "lib-rear-delt-fly",
    "name": "rearDeltFly",
    "bodyPart": "Shoulders",
    "description": "rearDeltFlyDescription",
    "emoji": "🤷",
    "tracking": "weight",
    "illustration": "rear-delt-fly"
  },
  {
    "id": "lib-reverse-pec-deck",
    "name": "reversePecDeck",
    "bodyPart": "Shoulders",
    "description": "reversePecDeckDescription",
    "emoji": "🤷",
    "tracking": "weight",
    "illustration": "reverse-pec-deck"
  },
  {
    "id": "lib-face-pull",
    "name": "facePull",
    "bodyPart": "Back",
    "description": "facePullDescription",
    "emoji": "🧗",
    "tracking": "weight",
    "illustration": "face-pull"
  },
  {
    "id": "lib-upright-row",
    "name": "uprightRow",
    "bodyPart": "Shoulders",
    "description": "uprightRowDescription",
    "emoji": "🤷",
    "tracking": "weight",
    "illustration": "upright-row"
  },
  {
    "id": "lib-romanian-deadlift",
    "name": "romanianDeadlift",
    "bodyPart": "Legs",
    "description": "romanianDeadliftDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "romanian-deadlift"
  },
  {
    "id": "lib-t-bar-row",
    "name": "tBarRow",
    "bodyPart": "Back",
    "description": "tBarRowDescription",
    "emoji": "🧗",
    "tracking": "weight",
    "illustration": "t-bar-row"
  },
  {
    "id": "lib-dumbbell-bent-over-row",
    "name": "dumbbellBentOverRow",
    "bodyPart": "Back",
    "description": "dumbbellBentOverRowDescription",
    "emoji": "🧗",
    "tracking": "weight",
    "illustration": "dumbbell-bent-over-row"
  },
  {
    "id": "lib-one-arm-dumbbell-row",
    "name": "oneArmDumbbellRow",
    "bodyPart": "Back",
    "description": "oneArmDumbbellRowDescription",
    "emoji": "🧗",
    "tracking": "weight",
    "illustration": "one-arm-dumbbell-row"
  },
  {
    "id": "lib-chest-supported-row",
    "name": "chestSupportedRow",
    "bodyPart": "Back",
    "description": "chestSupportedRowDescription",
    "emoji": "🧗",
    "tracking": "weight",
    "illustration": "chest-supported-row"
  },
  {
    "id": "lib-seated-row",
    "name": "seatedRow",
    "bodyPart": "Back",
    "description": "seatedRowDescription",
    "emoji": "🧗",
    "tracking": "weight",
    "illustration": "seated-row"
  },
  {
    "id": "lib-machine-row",
    "name": "machineRow",
    "bodyPart": "Back",
    "description": "machineRowDescription",
    "emoji": "🧗",
    "tracking": "weight",
    "illustration": "machine-row"
  },
  {
    "id": "lib-lat-pulldown",
    "name": "latPulldown",
    "bodyPart": "Back",
    "description": "latPulldownDescription",
    "emoji": "🧗",
    "tracking": "weight",
    "illustration": "lat-pulldown"
  },
  {
    "id": "lib-close-grip-lat-pulldown",
    "name": "closeGripLatPulldown",
    "bodyPart": "Back",
    "description": "closeGripLatPulldownDescription",
    "emoji": "🧗",
    "tracking": "weight",
    "illustration": "close-grip-lat-pulldown"
  },
  {
    "id": "lib-straight-arm-pulldown",
    "name": "straightArmPulldown",
    "bodyPart": "Back",
    "description": "straightArmPulldownDescription",
    "emoji": "🧗",
    "tracking": "weight",
    "illustration": "straight-arm-pulldown"
  },
  {
    "id": "lib-assisted-pull-up",
    "name": "assistedPullUp",
    "bodyPart": "Back",
    "description": "assistedPullUpDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "assisted-pull-up"
  },
  {
    "id": "lib-weighted-pull-up",
    "name": "weightedPullUp",
    "bodyPart": "Back",
    "description": "weightedPullUpDescription",
    "emoji": "🧗",
    "tracking": "weight",
    "illustration": "weighted-pull-up"
  },
  {
    "id": "lib-chin-up",
    "name": "chinUp",
    "bodyPart": "Arms",
    "description": "chinUpDescription",
    "emoji": "💪",
    "tracking": "bodyweight",
    "illustration": "chin-up"
  },
  {
    "id": "lib-shrug",
    "name": "shrug",
    "bodyPart": "Back",
    "description": "shrugDescription",
    "emoji": "🧗",
    "tracking": "weight",
    "illustration": "shrug"
  },
  {
    "id": "lib-front-squat",
    "name": "frontSquat",
    "bodyPart": "Legs",
    "description": "frontSquatDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "front-squat"
  },
  {
    "id": "lib-hack-squat",
    "name": "hackSquat",
    "bodyPart": "Legs",
    "description": "hackSquatDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "hack-squat"
  },
  {
    "id": "lib-bulgarian-split-squat",
    "name": "bulgarianSplitSquat",
    "bodyPart": "Legs",
    "description": "bulgarianSplitSquatDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "bulgarian-split-squat",
    "perSide": true
  },
  {
    "id": "lib-walking-lunge",
    "name": "walkingLunge",
    "bodyPart": "Legs",
    "description": "walkingLungeDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "walking-lunge",
    "perSide": true
  },
  {
    "id": "lib-step-up",
    "name": "stepUp",
    "bodyPart": "Legs",
    "description": "stepUpDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "step-up",
    "perSide": true
  },
  {
    "id": "lib-leg-extension",
    "name": "legExtension",
    "bodyPart": "Legs",
    "description": "legExtensionDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "leg-extension"
  },
  {
    "id": "lib-leg-curl",
    "name": "legCurl",
    "bodyPart": "Legs",
    "description": "legCurlDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "leg-curl"
  },
  {
    "id": "lib-seated-leg-curl",
    "name": "seatedLegCurl",
    "bodyPart": "Legs",
    "description": "seatedLegCurlDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "seated-leg-curl"
  },
  {
    "id": "lib-hip-thrust",
    "name": "hipThrust",
    "bodyPart": "Legs",
    "description": "hipThrustDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "hip-thrust"
  },
  {
    "id": "lib-glute-bridge",
    "name": "gluteBridge",
    "bodyPart": "Legs",
    "description": "gluteBridgeDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "glute-bridge"
  },
  {
    "id": "lib-good-morning",
    "name": "goodMorning",
    "bodyPart": "Legs",
    "description": "goodMorningDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "good-morning"
  },
  {
    "id": "lib-standing-calf-raise",
    "name": "standingCalfRaise",
    "bodyPart": "Legs",
    "description": "standingCalfRaiseDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "standing-calf-raise"
  },
  {
    "id": "lib-seated-calf-raise",
    "name": "seatedCalfRaise",
    "bodyPart": "Legs",
    "description": "seatedCalfRaiseDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "seated-calf-raise"
  },
  {
    "id": "lib-hammer-curl",
    "name": "hammerCurl",
    "bodyPart": "Arms",
    "description": "hammerCurlDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "hammer-curl"
  },
  {
    "id": "lib-preacher-curl",
    "name": "preacherCurl",
    "bodyPart": "Arms",
    "description": "preacherCurlDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "preacher-curl"
  },
  {
    "id": "lib-cable-curl",
    "name": "cableCurl",
    "bodyPart": "Arms",
    "description": "cableCurlDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "cable-curl"
  },
  {
    "id": "lib-reverse-curl",
    "name": "reverseCurl",
    "bodyPart": "Arms",
    "description": "reverseCurlDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "reverse-curl"
  },
  {
    "id": "lib-wrist-curl",
    "name": "wristCurl",
    "bodyPart": "Arms",
    "description": "wristCurlDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "wrist-curl"
  },
  {
    "id": "lib-tricep-pushdown",
    "name": "tricepPushdown",
    "bodyPart": "Arms",
    "description": "tricepPushdownDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "tricep-pushdown"
  },
  {
    "id": "lib-overhead-tricep-extension",
    "name": "overheadTricepExtension",
    "bodyPart": "Arms",
    "description": "overheadTricepExtensionDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "overhead-tricep-extension"
  },
  {
    "id": "lib-skull-crusher",
    "name": "skullCrusher",
    "bodyPart": "Arms",
    "description": "skullCrusherDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "skull-crusher"
  },
  {
    "id": "lib-close-grip-bench-press",
    "name": "closeGripBenchPress",
    "bodyPart": "Arms",
    "description": "closeGripBenchPressDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "close-grip-bench-press"
  },
  {
    "id": "lib-dip",
    "name": "dip",
    "bodyPart": "Arms",
    "description": "dipDescription",
    "emoji": "💪",
    "tracking": "bodyweight",
    "illustration": "dip"
  },
  {
    "id": "lib-assisted-dip",
    "name": "assistedDip",
    "bodyPart": "Arms",
    "description": "assistedDipDescription",
    "emoji": "💪",
    "tracking": "bodyweight",
    "illustration": "assisted-dip"
  },
  {
    "id": "lib-side-plank",
    "name": "sidePlank",
    "bodyPart": "Core",
    "description": "sidePlankDescription",
    "emoji": "🧘",
    "tracking": "duration",
    "illustration": "side-plank"
  },
  {
    "id": "lib-hanging-leg-raise",
    "name": "hangingLegRaise",
    "bodyPart": "Core",
    "description": "hangingLegRaiseDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "hanging-leg-raise"
  },
  {
    "id": "lib-cable-crunch",
    "name": "cableCrunch",
    "bodyPart": "Core",
    "description": "cableCrunchDescription",
    "emoji": "🧘",
    "tracking": "weight",
    "illustration": "cable-crunch"
  },
  {
    "id": "lib-ab-wheel",
    "name": "abWheel",
    "bodyPart": "Core",
    "description": "abWheelDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "ab-wheel"
  },
  {
    "id": "lib-running",
    "name": "running",
    "bodyPart": "Legs",
    "description": "runningDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "running"
  },
  {
    "id": "lib-walking",
    "name": "walking",
    "bodyPart": "Legs",
    "description": "walkingDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "walking"
  },
  {
    "id": "lib-cycling",
    "name": "cycling",
    "bodyPart": "Legs",
    "description": "cyclingDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "cycling"
  },
  {
    "id": "lib-rowing",
    "name": "rowing",
    "bodyPart": "Back",
    "description": "rowingDescription",
    "emoji": "🧗",
    "tracking": "duration",
    "illustration": "rowing"
  },
  {
    "id": "lib-stair-climber",
    "name": "stairClimber",
    "bodyPart": "Legs",
    "description": "stairClimberDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "stair-climber"
  },
  {
    "id": "lib-incline-cable-fly",
    "name": "inclineCableFly",
    "bodyPart": "Chest",
    "description": "inclineCableFlyDescription",
    "emoji": "🏋️",
    "tracking": "weight",
    "illustration": "incline-cable-fly"
  },
  {
    "id": "lib-decline-dumbbell-press",
    "name": "declineDumbbellPress",
    "bodyPart": "Chest",
    "description": "declineDumbbellPressDescription",
    "emoji": "🏋️",
    "tracking": "weight",
    "illustration": "decline-dumbbell-press"
  },
  {
    "id": "lib-smith-machine-bench-press",
    "name": "smithMachineBenchPress",
    "bodyPart": "Chest",
    "description": "smithMachineBenchPressDescription",
    "emoji": "🏋️",
    "tracking": "weight",
    "illustration": "smith-machine-bench-press"
  },
  {
    "id": "lib-landmine-press",
    "name": "landminePress",
    "bodyPart": "Shoulders",
    "description": "landminePressDescription",
    "emoji": "🤷",
    "tracking": "weight",
    "illustration": "landmine-press"
  },
  {
    "id": "lib-chest-dip",
    "name": "chestDip",
    "bodyPart": "Chest",
    "description": "chestDipDescription",
    "emoji": "🏋️",
    "tracking": "bodyweight",
    "illustration": "chest-dip"
  },
  {
    "id": "lib-weighted-dip",
    "name": "weightedDip",
    "bodyPart": "Arms",
    "description": "weightedDipDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "weighted-dip"
  },
  {
    "id": "lib-machine-shoulder-press",
    "name": "machineShoulderPress",
    "bodyPart": "Shoulders",
    "description": "machineShoulderPressDescription",
    "emoji": "🤷",
    "tracking": "weight",
    "illustration": "machine-shoulder-press"
  },
  {
    "id": "lib-standing-dumbbell-press",
    "name": "standingDumbbellPress",
    "bodyPart": "Shoulders",
    "description": "standingDumbbellPressDescription",
    "emoji": "🤷",
    "tracking": "weight",
    "illustration": "standing-dumbbell-press"
  },
  {
    "id": "lib-push-press",
    "name": "pushPress",
    "bodyPart": "Shoulders",
    "description": "pushPressDescription",
    "emoji": "🤷",
    "tracking": "weight",
    "illustration": "push-press"
  },
  {
    "id": "lib-machine-lateral-raise",
    "name": "machineLateralRaise",
    "bodyPart": "Shoulders",
    "description": "machineLateralRaiseDescription",
    "emoji": "🤷",
    "tracking": "weight",
    "illustration": "machine-lateral-raise"
  },
  {
    "id": "lib-cable-front-raise",
    "name": "cableFrontRaise",
    "bodyPart": "Shoulders",
    "description": "cableFrontRaiseDescription",
    "emoji": "🤷",
    "tracking": "weight",
    "illustration": "cable-front-raise"
  },
  {
    "id": "lib-plate-front-raise",
    "name": "plateFrontRaise",
    "bodyPart": "Shoulders",
    "description": "plateFrontRaiseDescription",
    "emoji": "🤷",
    "tracking": "weight",
    "illustration": "plate-front-raise"
  },
  {
    "id": "lib-bent-over-rear-delt-raise",
    "name": "bentOverRearDeltRaise",
    "bodyPart": "Shoulders",
    "description": "bentOverRearDeltRaiseDescription",
    "emoji": "🤷",
    "tracking": "weight",
    "illustration": "bent-over-rear-delt-raise"
  },
  {
    "id": "lib-cable-rear-delt-fly",
    "name": "cableRearDeltFly",
    "bodyPart": "Shoulders",
    "description": "cableRearDeltFlyDescription",
    "emoji": "🤷",
    "tracking": "weight",
    "illustration": "cable-rear-delt-fly"
  },
  {
    "id": "lib-pendlay-row",
    "name": "pendlayRow",
    "bodyPart": "Back",
    "description": "pendlayRowDescription",
    "emoji": "🧗",
    "tracking": "weight",
    "illustration": "pendlay-row"
  },
  {
    "id": "lib-inverted-row",
    "name": "invertedRow",
    "bodyPart": "Back",
    "description": "invertedRowDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "inverted-row"
  },
  {
    "id": "lib-meadows-row",
    "name": "meadowsRow",
    "bodyPart": "Back",
    "description": "meadowsRowDescription",
    "emoji": "🧗",
    "tracking": "weight",
    "illustration": "meadows-row"
  },
  {
    "id": "lib-single-arm-cable-row",
    "name": "singleArmCableRow",
    "bodyPart": "Back",
    "description": "singleArmCableRowDescription",
    "emoji": "🧗",
    "tracking": "weight",
    "illustration": "single-arm-cable-row"
  },
  {
    "id": "lib-wide-grip-lat-pulldown",
    "name": "wideGripLatPulldown",
    "bodyPart": "Back",
    "description": "wideGripLatPulldownDescription",
    "emoji": "🧗",
    "tracking": "weight",
    "illustration": "wide-grip-lat-pulldown"
  },
  {
    "id": "lib-neutral-grip-pull-up",
    "name": "neutralGripPullUp",
    "bodyPart": "Back",
    "description": "neutralGripPullUpDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "neutral-grip-pull-up"
  },
  {
    "id": "lib-assisted-chin-up",
    "name": "assistedChinUp",
    "bodyPart": "Arms",
    "description": "assistedChinUpDescription",
    "emoji": "💪",
    "tracking": "bodyweight",
    "illustration": "assisted-chin-up"
  },
  {
    "id": "lib-weighted-chin-up",
    "name": "weightedChinUp",
    "bodyPart": "Arms",
    "description": "weightedChinUpDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "weighted-chin-up"
  },
  {
    "id": "lib-rack-pull",
    "name": "rackPull",
    "bodyPart": "Back",
    "description": "rackPullDescription",
    "emoji": "🧗",
    "tracking": "weight",
    "illustration": "rack-pull"
  },
  {
    "id": "lib-back-extension",
    "name": "backExtension",
    "bodyPart": "Back",
    "description": "backExtensionDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "back-extension"
  },
  {
    "id": "lib-dumbbell-shrug",
    "name": "dumbbellShrug",
    "bodyPart": "Back",
    "description": "dumbbellShrugDescription",
    "emoji": "🧗",
    "tracking": "weight",
    "illustration": "dumbbell-shrug"
  },
  {
    "id": "lib-goblet-squat",
    "name": "gobletSquat",
    "bodyPart": "Legs",
    "description": "gobletSquatDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "goblet-squat"
  },
  {
    "id": "lib-smith-machine-squat",
    "name": "smithMachineSquat",
    "bodyPart": "Legs",
    "description": "smithMachineSquatDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "smith-machine-squat"
  },
  {
    "id": "lib-belt-squat",
    "name": "beltSquat",
    "bodyPart": "Legs",
    "description": "beltSquatDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "belt-squat"
  },
  {
    "id": "lib-sumo-deadlift",
    "name": "sumoDeadlift",
    "bodyPart": "Legs",
    "description": "sumoDeadliftDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "sumo-deadlift"
  },
  {
    "id": "lib-trap-bar-deadlift",
    "name": "trapBarDeadlift",
    "bodyPart": "Legs",
    "description": "trapBarDeadliftDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "trap-bar-deadlift"
  },
  {
    "id": "lib-lying-leg-curl",
    "name": "lyingLegCurl",
    "bodyPart": "Legs",
    "description": "lyingLegCurlDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "lying-leg-curl"
  },
  {
    "id": "lib-nordic-hamstring-curl",
    "name": "nordicHamstringCurl",
    "bodyPart": "Legs",
    "description": "nordicHamstringCurlDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "nordic-hamstring-curl"
  },
  {
    "id": "lib-single-leg-romanian-deadlift",
    "name": "singleLegRomanianDeadlift",
    "bodyPart": "Legs",
    "description": "singleLegRomanianDeadliftDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "single-leg-romanian-deadlift"
  },
  {
    "id": "lib-reverse-lunge",
    "name": "reverseLunge",
    "bodyPart": "Legs",
    "description": "reverseLungeDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "reverse-lunge",
    "perSide": true
  },
  {
    "id": "lib-split-squat",
    "name": "splitSquat",
    "bodyPart": "Legs",
    "description": "splitSquatDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "split-squat",
    "perSide": true
  },
  {
    "id": "lib-cable-kickback",
    "name": "cableKickback",
    "bodyPart": "Legs",
    "description": "cableKickbackDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "cable-kickback"
  },
  {
    "id": "lib-hip-abduction-machine",
    "name": "hipAbductionMachine",
    "bodyPart": "Legs",
    "description": "hipAbductionMachineDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "hip-abduction-machine"
  },
  {
    "id": "lib-single-leg-glute-bridge",
    "name": "singleLegGluteBridge",
    "bodyPart": "Legs",
    "description": "singleLegGluteBridgeDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "single-leg-glute-bridge"
  },
  {
    "id": "lib-barbell-glute-bridge",
    "name": "barbellGluteBridge",
    "bodyPart": "Legs",
    "description": "barbellGluteBridgeDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "barbell-glute-bridge"
  },
  {
    "id": "lib-dumbbell-glute-bridge",
    "name": "dumbbellGluteBridge",
    "bodyPart": "Legs",
    "description": "dumbbellGluteBridgeDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "dumbbell-glute-bridge"
  },
  {
    "id": "lib-dumbbell-hip-thrust",
    "name": "dumbbellHipThrust",
    "bodyPart": "Legs",
    "description": "dumbbellHipThrustDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "dumbbell-hip-thrust"
  },
  {
    "id": "lib-smith-machine-hip-thrust",
    "name": "smithMachineHipThrust",
    "bodyPart": "Legs",
    "description": "smithMachineHipThrustDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "smith-machine-hip-thrust"
  },
  {
    "id": "lib-smith-machine-romanian-deadlift",
    "name": "smithMachineRomanianDeadlift",
    "bodyPart": "Legs",
    "description": "smithMachineRomanianDeadliftDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "smith-machine-romanian-deadlift"
  },
  {
    "id": "lib-dumbbell-romanian-deadlift",
    "name": "dumbbellRomanianDeadlift",
    "bodyPart": "Legs",
    "description": "dumbbellRomanianDeadliftDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "dumbbell-romanian-deadlift"
  },
  {
    "id": "lib-kettlebell-romanian-deadlift",
    "name": "kettlebellRomanianDeadlift",
    "bodyPart": "Legs",
    "description": "kettlebellRomanianDeadliftDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "kettlebell-romanian-deadlift"
  },
  {
    "id": "lib-cable-pull-through",
    "name": "cablePullThrough",
    "bodyPart": "Legs",
    "description": "cablePullThroughDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "cable-pull-through"
  },
  {
    "id": "lib-machine-glute-kickback",
    "name": "machineGluteKickback",
    "bodyPart": "Legs",
    "description": "machineGluteKickbackDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "machine-glute-kickback"
  },
  {
    "id": "lib-cable-standing-hip-abduction",
    "name": "cableStandingHipAbduction",
    "bodyPart": "Legs",
    "description": "cableStandingHipAbductionDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "cable-standing-hip-abduction"
  },
  {
    "id": "lib-cable-standing-hip-adduction",
    "name": "cableStandingHipAdduction",
    "bodyPart": "Legs",
    "description": "cableStandingHipAdductionDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "cable-standing-hip-adduction"
  },
  {
    "id": "lib-hip-adduction-machine",
    "name": "hipAdductionMachine",
    "bodyPart": "Legs",
    "description": "hipAdductionMachineDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "hip-adduction-machine"
  },
  {
    "id": "lib-smith-machine-bulgarian-split-squat",
    "name": "smithMachineBulgarianSplitSquat",
    "bodyPart": "Legs",
    "description": "smithMachineBulgarianSplitSquatDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "smith-machine-bulgarian-split-squat",
    "perSide": true
  },
  {
    "id": "lib-smith-machine-reverse-lunge",
    "name": "smithMachineReverseLunge",
    "bodyPart": "Legs",
    "description": "smithMachineReverseLungeDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "smith-machine-reverse-lunge",
    "perSide": true
  },
  {
    "id": "lib-smith-machine-split-squat",
    "name": "smithMachineSplitSquat",
    "bodyPart": "Legs",
    "description": "smithMachineSplitSquatDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "smith-machine-split-squat",
    "perSide": true
  },
  {
    "id": "lib-heel-elevated-goblet-squat",
    "name": "heelElevatedGobletSquat",
    "bodyPart": "Legs",
    "description": "heelElevatedGobletSquatDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "heel-elevated-goblet-squat"
  },
  {
    "id": "lib-dumbbell-sumo-squat",
    "name": "dumbbellSumoSquat",
    "bodyPart": "Legs",
    "description": "dumbbellSumoSquatDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "dumbbell-sumo-squat"
  },
  {
    "id": "lib-dumbbell-sumo-deadlift",
    "name": "dumbbellSumoDeadlift",
    "bodyPart": "Legs",
    "description": "dumbbellSumoDeadliftDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "dumbbell-sumo-deadlift"
  },
  {
    "id": "lib-front-foot-elevated-split-squat",
    "name": "frontFootElevatedSplitSquat",
    "bodyPart": "Legs",
    "description": "frontFootElevatedSplitSquatDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "front-foot-elevated-split-squat",
    "perSide": true
  },
  {
    "id": "lib-deficit-reverse-lunge",
    "name": "deficitReverseLunge",
    "bodyPart": "Legs",
    "description": "deficitReverseLungeDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "deficit-reverse-lunge",
    "perSide": true
  },
  {
    "id": "lib-dumbbell-lateral-lunge",
    "name": "dumbbellLateralLunge",
    "bodyPart": "Legs",
    "description": "dumbbellLateralLungeDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "dumbbell-lateral-lunge",
    "perSide": true
  },
  {
    "id": "lib-dumbbell-curtsy-lunge",
    "name": "dumbbellCurtsyLunge",
    "bodyPart": "Legs",
    "description": "dumbbellCurtsyLungeDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "dumbbell-curtsy-lunge",
    "perSide": true
  },
  {
    "id": "lib-landmine-squat",
    "name": "landmineSquat",
    "bodyPart": "Legs",
    "description": "landmineSquatDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "landmine-squat"
  },
  {
    "id": "lib-landmine-romanian-deadlift",
    "name": "landmineRomanianDeadlift",
    "bodyPart": "Legs",
    "description": "landmineRomanianDeadliftDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "landmine-romanian-deadlift"
  },
  {
    "id": "lib-kettlebell-swing",
    "name": "kettlebellSwing",
    "bodyPart": "Legs",
    "description": "kettlebellSwingDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "kettlebell-swing"
  },
  {
    "id": "lib-glute-focused-back-extension",
    "name": "gluteFocusedBackExtension",
    "bodyPart": "Legs",
    "description": "gluteFocusedBackExtensionDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "glute-focused-back-extension"
  },
  {
    "id": "lib-reverse-hyperextension",
    "name": "reverseHyperextension",
    "bodyPart": "Legs",
    "description": "reverseHyperextensionDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "reverse-hyperextension"
  },
  {
    "id": "lib-donkey-calf-raise",
    "name": "donkeyCalfRaise",
    "bodyPart": "Legs",
    "description": "donkeyCalfRaiseDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "donkey-calf-raise"
  },
  {
    "id": "lib-leg-press-calf-raise",
    "name": "legPressCalfRaise",
    "bodyPart": "Legs",
    "description": "legPressCalfRaiseDescription",
    "emoji": "🏃",
    "tracking": "weight",
    "illustration": "leg-press-calf-raise"
  },
  {
    "id": "lib-wall-sit",
    "name": "wallSit",
    "bodyPart": "Legs",
    "description": "wallSitDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "wall-sit"
  },
  {
    "id": "lib-jump-squat",
    "name": "jumpSquat",
    "bodyPart": "Legs",
    "description": "jumpSquatDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "jump-squat"
  },
  {
    "id": "lib-incline-dumbbell-curl",
    "name": "inclineDumbbellCurl",
    "bodyPart": "Arms",
    "description": "inclineDumbbellCurlDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "incline-dumbbell-curl"
  },
  {
    "id": "lib-concentration-curl",
    "name": "concentrationCurl",
    "bodyPart": "Arms",
    "description": "concentrationCurlDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "concentration-curl"
  },
  {
    "id": "lib-ez-bar-curl",
    "name": "ezBarCurl",
    "bodyPart": "Arms",
    "description": "ezBarCurlDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "ez-bar-curl"
  },
  {
    "id": "lib-spider-curl",
    "name": "spiderCurl",
    "bodyPart": "Arms",
    "description": "spiderCurlDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "spider-curl"
  },
  {
    "id": "lib-rope-hammer-curl",
    "name": "ropeHammerCurl",
    "bodyPart": "Arms",
    "description": "ropeHammerCurlDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "rope-hammer-curl"
  },
  {
    "id": "lib-drag-curl",
    "name": "dragCurl",
    "bodyPart": "Arms",
    "description": "dragCurlDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "drag-curl"
  },
  {
    "id": "lib-rope-tricep-pushdown",
    "name": "ropeTricepPushdown",
    "bodyPart": "Arms",
    "description": "ropeTricepPushdownDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "rope-tricep-pushdown"
  },
  {
    "id": "lib-dumbbell-skull-crusher",
    "name": "dumbbellSkullCrusher",
    "bodyPart": "Arms",
    "description": "dumbbellSkullCrusherDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "dumbbell-skull-crusher"
  },
  {
    "id": "lib-single-dumbbell-skullcrusher",
    "name": "singleDumbbellSkullcrusher",
    "bodyPart": "Arms",
    "description": "singleDumbbellSkullcrusherDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "single-dumbbell-skullcrusher"
  },
  {
    "id": "lib-dumbbell-overhead-tricep-extension",
    "name": "dumbbellOverheadTricepExtension",
    "bodyPart": "Arms",
    "description": "dumbbellOverheadTricepExtensionDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "dumbbell-overhead-tricep-extension"
  },
  {
    "id": "lib-single-arm-dumbbell-tricep-extension",
    "name": "singleArmDumbbellTricepExtension",
    "bodyPart": "Arms",
    "description": "singleArmDumbbellTricepExtensionDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "single-arm-dumbbell-tricep-extension"
  },
  {
    "id": "lib-tricep-kickback",
    "name": "tricepKickback",
    "bodyPart": "Arms",
    "description": "tricepKickbackDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "tricep-kickback"
  },
  {
    "id": "lib-wrist-extension",
    "name": "wristExtension",
    "bodyPart": "Arms",
    "description": "wristExtensionDescription",
    "emoji": "💪",
    "tracking": "weight",
    "illustration": "wrist-extension"
  },
  {
    "id": "lib-farmer-carry",
    "name": "farmerCarry",
    "bodyPart": "Arms",
    "description": "farmerCarryDescription",
    "emoji": "💪",
    "tracking": "duration",
    "illustration": "farmer-carry"
  },
  {
    "id": "lib-reverse-crunch",
    "name": "reverseCrunch",
    "bodyPart": "Core",
    "description": "reverseCrunchDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "reverse-crunch"
  },
  {
    "id": "lib-russian-twist",
    "name": "russianTwist",
    "bodyPart": "Core",
    "description": "russianTwistDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "russian-twist"
  },
  {
    "id": "lib-bicycle-crunch",
    "name": "bicycleCrunch",
    "bodyPart": "Core",
    "description": "bicycleCrunchDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "bicycle-crunch"
  },
  {
    "id": "lib-mountain-climber",
    "name": "mountainClimber",
    "bodyPart": "Core",
    "description": "mountainClimberDescription",
    "emoji": "🧘",
    "tracking": "duration",
    "illustration": "mountain-climber"
  },
  {
    "id": "lib-dead-bug",
    "name": "deadBug",
    "bodyPart": "Core",
    "description": "deadBugDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "dead-bug"
  },
  {
    "id": "lib-bird-dog",
    "name": "birdDog",
    "bodyPart": "Core",
    "description": "birdDogDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "bird-dog"
  },
  {
    "id": "lib-pallof-press",
    "name": "pallofPress",
    "bodyPart": "Core",
    "description": "pallofPressDescription",
    "emoji": "🧘",
    "tracking": "weight",
    "illustration": "pallof-press"
  },
  {
    "id": "lib-cable-woodchop",
    "name": "cableWoodchop",
    "bodyPart": "Core",
    "description": "cableWoodchopDescription",
    "emoji": "🧘",
    "tracking": "weight",
    "illustration": "cable-woodchop"
  },
  {
    "id": "lib-half-kneeling-pallof-press",
    "name": "halfKneelingPallofPress",
    "bodyPart": "Core",
    "description": "halfKneelingPallofPressDescription",
    "emoji": "🧘",
    "tracking": "weight",
    "illustration": "half-kneeling-pallof-press"
  },
  {
    "id": "lib-cable-pallof-hold",
    "name": "cablePallofHold",
    "bodyPart": "Core",
    "description": "cablePallofHoldDescription",
    "emoji": "🧘",
    "tracking": "duration",
    "illustration": "cable-pallof-hold"
  },
  {
    "id": "lib-hanging-knee-raise",
    "name": "hangingKneeRaise",
    "bodyPart": "Core",
    "description": "hangingKneeRaiseDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "hanging-knee-raise"
  },
  {
    "id": "lib-captains-chair-knee-raise",
    "name": "captainsChairKneeRaise",
    "bodyPart": "Core",
    "description": "captainsChairKneeRaiseDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "captains-chair-knee-raise"
  },
  {
    "id": "lib-decline-sit-up",
    "name": "declineSitUp",
    "bodyPart": "Core",
    "description": "declineSitUpDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "decline-sit-up"
  },
  {
    "id": "lib-weighted-crunch",
    "name": "weightedCrunch",
    "bodyPart": "Core",
    "description": "weightedCrunchDescription",
    "emoji": "🧘",
    "tracking": "weight",
    "illustration": "weighted-crunch"
  },
  {
    "id": "lib-weighted-russian-twist",
    "name": "weightedRussianTwist",
    "bodyPart": "Core",
    "description": "weightedRussianTwistDescription",
    "emoji": "🧘",
    "tracking": "weight",
    "illustration": "weighted-russian-twist"
  },
  {
    "id": "lib-dumbbell-side-bend",
    "name": "dumbbellSideBend",
    "bodyPart": "Core",
    "description": "dumbbellSideBendDescription",
    "emoji": "🧘",
    "tracking": "weight",
    "illustration": "dumbbell-side-bend"
  },
  {
    "id": "lib-elliptical",
    "name": "elliptical",
    "bodyPart": "Legs",
    "description": "ellipticalDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "elliptical"
  },
  {
    "id": "lib-swimming",
    "name": "swimming",
    "bodyPart": "Back",
    "description": "swimmingDescription",
    "emoji": "🧗",
    "tracking": "duration",
    "illustration": "swimming"
  },
  {
    "id": "lib-jump-rope",
    "name": "jumpRope",
    "bodyPart": "Legs",
    "description": "jumpRopeDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "jump-rope"
  },
  {
    "id": "lib-assault-bike",
    "name": "assaultBike",
    "bodyPart": "Legs",
    "description": "assaultBikeDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "assault-bike"
  },
  {
    "id": "lib-skierg",
    "name": "skierg",
    "bodyPart": "Back",
    "description": "skiergDescription",
    "emoji": "🧗",
    "tracking": "duration",
    "illustration": "skierg"
  },
  {
    "id": "lib-hiking",
    "name": "hiking",
    "bodyPart": "Legs",
    "description": "hikingDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "hiking"
  },
  {
    "id": "lib-treadmill-incline-walk",
    "name": "treadmillInclineWalk",
    "bodyPart": "Legs",
    "description": "treadmillInclineWalkDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "treadmill-incline-walk"
  },
  {
    "id": "lib-battle-ropes",
    "name": "battleRopes",
    "bodyPart": "Shoulders",
    "description": "battleRopesDescription",
    "emoji": "🤷",
    "tracking": "duration",
    "illustration": "battle-ropes"
  },
  {
    "id": "lib-incline-push-up",
    "name": "inclinePushUp",
    "bodyPart": "Chest",
    "description": "inclinePushUpDescription",
    "emoji": "🏋️",
    "tracking": "bodyweight",
    "illustration": "incline-push-up"
  },
  {
    "id": "lib-knee-push-up",
    "name": "kneePushUp",
    "bodyPart": "Chest",
    "description": "kneePushUpDescription",
    "emoji": "🏋️",
    "tracking": "bodyweight",
    "illustration": "knee-push-up"
  },
  {
    "id": "lib-wide-push-up",
    "name": "widePushUp",
    "bodyPart": "Chest",
    "description": "widePushUpDescription",
    "emoji": "🏋️",
    "tracking": "bodyweight",
    "illustration": "wide-push-up"
  },
  {
    "id": "lib-diamond-push-up",
    "name": "diamondPushUp",
    "bodyPart": "Arms",
    "description": "diamondPushUpDescription",
    "emoji": "💪",
    "tracking": "bodyweight",
    "illustration": "diamond-push-up"
  },
  {
    "id": "lib-decline-push-up",
    "name": "declinePushUp",
    "bodyPart": "Chest",
    "description": "declinePushUpDescription",
    "emoji": "🏋️",
    "tracking": "bodyweight",
    "illustration": "decline-push-up"
  },
  {
    "id": "lib-pike-push-up",
    "name": "pikePushUp",
    "bodyPart": "Shoulders",
    "description": "pikePushUpDescription",
    "emoji": "🤷",
    "tracking": "bodyweight",
    "illustration": "pike-push-up"
  },
  {
    "id": "lib-feet-elevated-pike-push-up",
    "name": "feetElevatedPikePushUp",
    "bodyPart": "Shoulders",
    "description": "feetElevatedPikePushUpDescription",
    "emoji": "🤷",
    "tracking": "bodyweight",
    "illustration": "feet-elevated-pike-push-up"
  },
  {
    "id": "lib-archer-push-up",
    "name": "archerPushUp",
    "bodyPart": "Chest",
    "description": "archerPushUpDescription",
    "emoji": "🏋️",
    "tracking": "bodyweight",
    "illustration": "archer-push-up"
  },
  {
    "id": "lib-typewriter-push-up",
    "name": "typewriterPushUp",
    "bodyPart": "Chest",
    "description": "typewriterPushUpDescription",
    "emoji": "🏋️",
    "tracking": "bodyweight",
    "illustration": "typewriter-push-up"
  },
  {
    "id": "lib-explosive-push-up",
    "name": "explosivePushUp",
    "bodyPart": "Chest",
    "description": "explosivePushUpDescription",
    "emoji": "🏋️",
    "tracking": "bodyweight",
    "illustration": "explosive-push-up"
  },
  {
    "id": "lib-hindu-push-up",
    "name": "hinduPushUp",
    "bodyPart": "Chest",
    "description": "hinduPushUpDescription",
    "emoji": "🏋️",
    "tracking": "bodyweight",
    "illustration": "hindu-push-up"
  },
  {
    "id": "lib-scapular-push-up",
    "name": "scapularPushUp",
    "bodyPart": "Back",
    "description": "scapularPushUpDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "scapular-push-up"
  },
  {
    "id": "lib-push-up-shoulder-tap",
    "name": "pushUpShoulderTap",
    "bodyPart": "Core",
    "description": "pushUpShoulderTapDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "push-up-shoulder-tap"
  },
  {
    "id": "lib-wall-push-up",
    "name": "wallPushUp",
    "bodyPart": "Chest",
    "description": "wallPushUpDescription",
    "emoji": "🏋️",
    "tracking": "bodyweight",
    "illustration": "wall-push-up"
  },
  {
    "id": "lib-wall-walk",
    "name": "wallWalk",
    "bodyPart": "Shoulders",
    "description": "wallWalkDescription",
    "emoji": "🤷",
    "tracking": "bodyweight",
    "illustration": "wall-walk"
  },
  {
    "id": "lib-wall-handstand-push-up",
    "name": "wallHandstandPushUp",
    "bodyPart": "Shoulders",
    "description": "wallHandstandPushUpDescription",
    "emoji": "🤷",
    "tracking": "bodyweight",
    "illustration": "wall-handstand-push-up"
  },
  {
    "id": "lib-handstand-push-up",
    "name": "handstandPushUp",
    "bodyPart": "Shoulders",
    "description": "handstandPushUpDescription",
    "emoji": "🤷",
    "tracking": "bodyweight",
    "illustration": "handstand-push-up"
  },
  {
    "id": "lib-chair-dip",
    "name": "chairDip",
    "bodyPart": "Arms",
    "description": "chairDipDescription",
    "emoji": "💪",
    "tracking": "bodyweight",
    "illustration": "chair-dip"
  },
  {
    "id": "lib-doorway-row",
    "name": "doorwayRow",
    "bodyPart": "Back",
    "description": "doorwayRowDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "doorway-row"
  },
  {
    "id": "lib-towel-row",
    "name": "towelRow",
    "bodyPart": "Back",
    "description": "towelRowDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "towel-row"
  },
  {
    "id": "lib-prone-y-raise",
    "name": "proneYRaise",
    "bodyPart": "Back",
    "description": "proneYRaiseDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "prone-y-raise"
  },
  {
    "id": "lib-prone-t-raise",
    "name": "proneTRaise",
    "bodyPart": "Back",
    "description": "proneTRaiseDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "prone-t-raise"
  },
  {
    "id": "lib-superman",
    "name": "superman",
    "bodyPart": "Back",
    "description": "supermanDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "superman"
  },
  {
    "id": "lib-superman-hold",
    "name": "supermanHold",
    "bodyPart": "Back",
    "description": "supermanHoldDescription",
    "emoji": "🧗",
    "tracking": "duration",
    "illustration": "superman-hold"
  },
  {
    "id": "lib-reverse-snow-angel",
    "name": "reverseSnowAngel",
    "bodyPart": "Back",
    "description": "reverseSnowAngelDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "reverse-snow-angel"
  },
  {
    "id": "lib-dead-hang",
    "name": "deadHang",
    "bodyPart": "Arms",
    "description": "deadHangDescription",
    "emoji": "💪",
    "tracking": "duration",
    "illustration": "dead-hang"
  },
  {
    "id": "lib-active-hang",
    "name": "activeHang",
    "bodyPart": "Back",
    "description": "activeHangDescription",
    "emoji": "🧗",
    "tracking": "duration",
    "illustration": "active-hang"
  },
  {
    "id": "lib-scapular-pull-up",
    "name": "scapularPullUp",
    "bodyPart": "Back",
    "description": "scapularPullUpDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "scapular-pull-up"
  },
  {
    "id": "lib-negative-pull-up",
    "name": "negativePullUp",
    "bodyPart": "Back",
    "description": "negativePullUpDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "negative-pull-up"
  },
  {
    "id": "lib-commando-pull-up",
    "name": "commandoPullUp",
    "bodyPart": "Back",
    "description": "commandoPullUpDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "commando-pull-up"
  },
  {
    "id": "lib-l-sit-pull-up",
    "name": "lSitPullUp",
    "bodyPart": "Back",
    "description": "lSitPullUpDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "l-sit-pull-up"
  },
  {
    "id": "lib-towel-pull-up",
    "name": "towelPullUp",
    "bodyPart": "Back",
    "description": "towelPullUpDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "towel-pull-up"
  },
  {
    "id": "lib-bodyweight-squat",
    "name": "bodyweightSquat",
    "bodyPart": "Legs",
    "description": "bodyweightSquatDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "bodyweight-squat"
  },
  {
    "id": "lib-pistol-squat",
    "name": "pistolSquat",
    "bodyPart": "Legs",
    "description": "pistolSquatDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "pistol-squat"
  },
  {
    "id": "lib-assisted-pistol-squat",
    "name": "assistedPistolSquat",
    "bodyPart": "Legs",
    "description": "assistedPistolSquatDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "assisted-pistol-squat"
  },
  {
    "id": "lib-shrimp-squat",
    "name": "shrimpSquat",
    "bodyPart": "Legs",
    "description": "shrimpSquatDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "shrimp-squat"
  },
  {
    "id": "lib-cossack-squat",
    "name": "cossackSquat",
    "bodyPart": "Legs",
    "description": "cossackSquatDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "cossack-squat"
  },
  {
    "id": "lib-sissy-squat",
    "name": "sissySquat",
    "bodyPart": "Legs",
    "description": "sissySquatDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "sissy-squat"
  },
  {
    "id": "lib-lateral-lunge",
    "name": "lateralLunge",
    "bodyPart": "Legs",
    "description": "lateralLungeDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "lateral-lunge",
    "perSide": true
  },
  {
    "id": "lib-curtsy-lunge",
    "name": "curtsyLunge",
    "bodyPart": "Legs",
    "description": "curtsyLungeDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "curtsy-lunge",
    "perSide": true
  },
  {
    "id": "lib-skater-squat",
    "name": "skaterSquat",
    "bodyPart": "Legs",
    "description": "skaterSquatDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "skater-squat"
  },
  {
    "id": "lib-single-leg-box-squat",
    "name": "singleLegBoxSquat",
    "bodyPart": "Legs",
    "description": "singleLegBoxSquatDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "single-leg-box-squat"
  },
  {
    "id": "lib-step-down",
    "name": "stepDown",
    "bodyPart": "Legs",
    "description": "stepDownDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "step-down",
    "perSide": true
  },
  {
    "id": "lib-calf-raise",
    "name": "calfRaise",
    "bodyPart": "Legs",
    "description": "calfRaiseDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "calf-raise"
  },
  {
    "id": "lib-single-leg-calf-raise",
    "name": "singleLegCalfRaise",
    "bodyPart": "Legs",
    "description": "singleLegCalfRaiseDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "single-leg-calf-raise"
  },
  {
    "id": "lib-glute-bridge-march",
    "name": "gluteBridgeMarch",
    "bodyPart": "Legs",
    "description": "gluteBridgeMarchDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "glute-bridge-march"
  },
  {
    "id": "lib-frog-pump",
    "name": "frogPump",
    "bodyPart": "Legs",
    "description": "frogPumpDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "frog-pump"
  },
  {
    "id": "lib-donkey-kick",
    "name": "donkeyKick",
    "bodyPart": "Legs",
    "description": "donkeyKickDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "donkey-kick"
  },
  {
    "id": "lib-fire-hydrant",
    "name": "fireHydrant",
    "bodyPart": "Legs",
    "description": "fireHydrantDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "fire-hydrant"
  },
  {
    "id": "lib-clamshell",
    "name": "clamshell",
    "bodyPart": "Legs",
    "description": "clamshellDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "clamshell"
  },
  {
    "id": "lib-hip-airplane",
    "name": "hipAirplane",
    "bodyPart": "Legs",
    "description": "hipAirplaneDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "hip-airplane"
  },
  {
    "id": "lib-side-lying-hip-abduction",
    "name": "sideLyingHipAbduction",
    "bodyPart": "Legs",
    "description": "sideLyingHipAbductionDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "side-lying-hip-abduction"
  },
  {
    "id": "lib-side-lying-leg-raise",
    "name": "sideLyingLegRaise",
    "bodyPart": "Legs",
    "description": "sideLyingLegRaiseDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "side-lying-leg-raise"
  },
  {
    "id": "lib-lying-hamstring-walkout",
    "name": "lyingHamstringWalkout",
    "bodyPart": "Legs",
    "description": "lyingHamstringWalkoutDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "lying-hamstring-walkout"
  },
  {
    "id": "lib-towel-hamstring-curl",
    "name": "towelHamstringCurl",
    "bodyPart": "Legs",
    "description": "towelHamstringCurlDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "towel-hamstring-curl"
  },
  {
    "id": "lib-stability-ball-hamstring-curl",
    "name": "stabilityBallHamstringCurl",
    "bodyPart": "Legs",
    "description": "stabilityBallHamstringCurlDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "stability-ball-hamstring-curl"
  },
  {
    "id": "lib-banded-glute-bridge",
    "name": "bandedGluteBridge",
    "bodyPart": "Legs",
    "description": "bandedGluteBridgeDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "banded-glute-bridge"
  },
  {
    "id": "lib-banded-hip-thrust",
    "name": "bandedHipThrust",
    "bodyPart": "Legs",
    "description": "bandedHipThrustDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "banded-hip-thrust"
  },
  {
    "id": "lib-banded-frog-pump",
    "name": "bandedFrogPump",
    "bodyPart": "Legs",
    "description": "bandedFrogPumpDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "banded-frog-pump"
  },
  {
    "id": "lib-banded-clamshell",
    "name": "bandedClamshell",
    "bodyPart": "Legs",
    "description": "bandedClamshellDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "banded-clamshell"
  },
  {
    "id": "lib-banded-lateral-walk",
    "name": "bandedLateralWalk",
    "bodyPart": "Legs",
    "description": "bandedLateralWalkDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "banded-lateral-walk"
  },
  {
    "id": "lib-banded-monster-walk",
    "name": "bandedMonsterWalk",
    "bodyPart": "Legs",
    "description": "bandedMonsterWalkDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "banded-monster-walk"
  },
  {
    "id": "lib-banded-squat",
    "name": "bandedSquat",
    "bodyPart": "Legs",
    "description": "bandedSquatDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "banded-squat"
  },
  {
    "id": "lib-banded-donkey-kick",
    "name": "bandedDonkeyKick",
    "bodyPart": "Legs",
    "description": "bandedDonkeyKickDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "banded-donkey-kick"
  },
  {
    "id": "lib-banded-fire-hydrant",
    "name": "bandedFireHydrant",
    "bodyPart": "Legs",
    "description": "bandedFireHydrantDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "banded-fire-hydrant"
  },
  {
    "id": "lib-banded-kickback",
    "name": "bandedKickback",
    "bodyPart": "Legs",
    "description": "bandedKickbackDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "banded-kickback"
  },
  {
    "id": "lib-banded-standing-hip-abduction",
    "name": "bandedStandingHipAbduction",
    "bodyPart": "Legs",
    "description": "bandedStandingHipAbductionDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "banded-standing-hip-abduction"
  },
  {
    "id": "lib-banded-seated-hip-abduction",
    "name": "bandedSeatedHipAbduction",
    "bodyPart": "Legs",
    "description": "bandedSeatedHipAbductionDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "banded-seated-hip-abduction"
  },
  {
    "id": "lib-band-pull-apart",
    "name": "bandPullApart",
    "bodyPart": "Back",
    "description": "bandPullApartDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "band-pull-apart"
  },
  {
    "id": "lib-banded-face-pull",
    "name": "bandedFacePull",
    "bodyPart": "Back",
    "description": "bandedFacePullDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "banded-face-pull"
  },
  {
    "id": "lib-banded-row",
    "name": "bandedRow",
    "bodyPart": "Back",
    "description": "bandedRowDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "banded-row"
  },
  {
    "id": "lib-banded-lat-pulldown",
    "name": "bandedLatPulldown",
    "bodyPart": "Back",
    "description": "bandedLatPulldownDescription",
    "emoji": "🧗",
    "tracking": "bodyweight",
    "illustration": "banded-lat-pulldown"
  },
  {
    "id": "lib-banded-pallof-press",
    "name": "bandedPallofPress",
    "bodyPart": "Core",
    "description": "bandedPallofPressDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "banded-pallof-press"
  },
  {
    "id": "lib-banded-woodchop",
    "name": "bandedWoodchop",
    "bodyPart": "Core",
    "description": "bandedWoodchopDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "banded-woodchop"
  },
  {
    "id": "lib-banded-dead-bug",
    "name": "bandedDeadBug",
    "bodyPart": "Core",
    "description": "bandedDeadBugDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "banded-dead-bug"
  },
  {
    "id": "lib-hollow-body-hold",
    "name": "hollowBodyHold",
    "bodyPart": "Core",
    "description": "hollowBodyHoldDescription",
    "emoji": "🧘",
    "tracking": "duration",
    "illustration": "hollow-body-hold"
  },
  {
    "id": "lib-hollow-rock",
    "name": "hollowRock",
    "bodyPart": "Core",
    "description": "hollowRockDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "hollow-rock"
  },
  {
    "id": "lib-v-up",
    "name": "vUp",
    "bodyPart": "Core",
    "description": "vUpDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "v-up"
  },
  {
    "id": "lib-flutter-kick",
    "name": "flutterKick",
    "bodyPart": "Core",
    "description": "flutterKickDescription",
    "emoji": "🧘",
    "tracking": "duration",
    "illustration": "flutter-kick"
  },
  {
    "id": "lib-lying-leg-raise",
    "name": "lyingLegRaise",
    "bodyPart": "Core",
    "description": "lyingLegRaiseDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "lying-leg-raise"
  },
  {
    "id": "lib-toe-touch",
    "name": "toeTouch",
    "bodyPart": "Core",
    "description": "toeTouchDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "toe-touch"
  },
  {
    "id": "lib-heel-tap",
    "name": "heelTap",
    "bodyPart": "Core",
    "description": "heelTapDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "heel-tap"
  },
  {
    "id": "lib-plank-shoulder-tap",
    "name": "plankShoulderTap",
    "bodyPart": "Core",
    "description": "plankShoulderTapDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "plank-shoulder-tap"
  },
  {
    "id": "lib-plank-jack",
    "name": "plankJack",
    "bodyPart": "Core",
    "description": "plankJackDescription",
    "emoji": "🧘",
    "tracking": "duration",
    "illustration": "plank-jack"
  },
  {
    "id": "lib-bear-plank",
    "name": "bearPlank",
    "bodyPart": "Core",
    "description": "bearPlankDescription",
    "emoji": "🧘",
    "tracking": "duration",
    "illustration": "bear-plank"
  },
  {
    "id": "lib-bear-crawl",
    "name": "bearCrawl",
    "bodyPart": "Core",
    "description": "bearCrawlDescription",
    "emoji": "🧘",
    "tracking": "duration",
    "illustration": "bear-crawl"
  },
  {
    "id": "lib-crab-walk",
    "name": "crabWalk",
    "bodyPart": "Arms",
    "description": "crabWalkDescription",
    "emoji": "💪",
    "tracking": "duration",
    "illustration": "crab-walk"
  },
  {
    "id": "lib-inchworm",
    "name": "inchworm",
    "bodyPart": "Core",
    "description": "inchwormDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "inchworm"
  },
  {
    "id": "lib-l-sit-hold",
    "name": "lSitHold",
    "bodyPart": "Core",
    "description": "lSitHoldDescription",
    "emoji": "🧘",
    "tracking": "duration",
    "illustration": "l-sit-hold"
  },
  {
    "id": "lib-seated-knee-tuck",
    "name": "seatedKneeTuck",
    "bodyPart": "Core",
    "description": "seatedKneeTuckDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "seated-knee-tuck"
  },
  {
    "id": "lib-side-plank-hip-dip",
    "name": "sidePlankHipDip",
    "bodyPart": "Core",
    "description": "sidePlankHipDipDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "side-plank-hip-dip"
  },
  {
    "id": "lib-copenhagen-plank",
    "name": "copenhagenPlank",
    "bodyPart": "Core",
    "description": "copenhagenPlankDescription",
    "emoji": "🧘",
    "tracking": "duration",
    "illustration": "copenhagen-plank"
  },
  {
    "id": "lib-dragon-flag",
    "name": "dragonFlag",
    "bodyPart": "Core",
    "description": "dragonFlagDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "dragon-flag"
  },
  {
    "id": "lib-burpee",
    "name": "burpee",
    "bodyPart": "Legs",
    "description": "burpeeDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "burpee"
  },
  {
    "id": "lib-half-burpee",
    "name": "halfBurpee",
    "bodyPart": "Core",
    "description": "halfBurpeeDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "half-burpee"
  },
  {
    "id": "lib-squat-thrust",
    "name": "squatThrust",
    "bodyPart": "Core",
    "description": "squatThrustDescription",
    "emoji": "🧘",
    "tracking": "bodyweight",
    "illustration": "squat-thrust"
  },
  {
    "id": "lib-high-knees",
    "name": "highKnees",
    "bodyPart": "Legs",
    "description": "highKneesDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "high-knees"
  },
  {
    "id": "lib-jumping-jack",
    "name": "jumpingJack",
    "bodyPart": "Legs",
    "description": "jumpingJackDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "jumping-jack"
  },
  {
    "id": "lib-skater-hop",
    "name": "skaterHop",
    "bodyPart": "Legs",
    "description": "skaterHopDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "skater-hop"
  },
  {
    "id": "lib-lateral-shuffle",
    "name": "lateralShuffle",
    "bodyPart": "Legs",
    "description": "lateralShuffleDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "lateral-shuffle"
  },
  {
    "id": "lib-fast-feet",
    "name": "fastFeet",
    "bodyPart": "Legs",
    "description": "fastFeetDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "fast-feet"
  },
  {
    "id": "lib-sprawl",
    "name": "sprawl",
    "bodyPart": "Legs",
    "description": "sprawlDescription",
    "emoji": "🏃",
    "tracking": "bodyweight",
    "illustration": "sprawl"
  },
  {
    "id": "lib-seal-jack",
    "name": "sealJack",
    "bodyPart": "Chest",
    "description": "sealJackDescription",
    "emoji": "🏋️",
    "tracking": "duration",
    "illustration": "seal-jack"
  },
  {
    "id": "lib-cat-cow-stretch",
    "name": "catCowStretch",
    "bodyPart": "Core",
    "description": "catCowStretchDescription",
    "emoji": "🧘",
    "tracking": "duration",
    "illustration": "cat-cow-stretch"
  },
  {
    "id": "lib-arm-circles",
    "name": "armCircles",
    "bodyPart": "Shoulders",
    "description": "armCirclesDescription",
    "emoji": "🤷",
    "tracking": "duration",
    "illustration": "arm-circles"
  },
  {
    "id": "lib-worlds-greatest-stretch",
    "name": "worldsGreatestStretch",
    "bodyPart": "Core",
    "description": "worldsGreatestStretchDescription",
    "emoji": "🧘",
    "tracking": "duration",
    "illustration": "worlds-greatest-stretch"
  },
  {
    "id": "lib-leg-swings-stretch",
    "name": "legSwingsStretch",
    "bodyPart": "Core",
    "description": "legSwingsStretchDescription",
    "emoji": "🧘",
    "tracking": "duration",
    "illustration": "leg-swings-stretch"
  },
  {
    "id": "lib-torso-twist-stretch",
    "name": "torsoTwistStretch",
    "bodyPart": "Core",
    "description": "torsoTwistStretchDescription",
    "emoji": "🧘",
    "tracking": "duration",
    "illustration": "torso-twist-stretch"
  },
  {
    "id": "lib-doorway-chest-stretch",
    "name": "doorwayChestStretch",
    "bodyPart": "Chest",
    "description": "doorwayChestStretchDescription",
    "emoji": "🏋️",
    "tracking": "duration",
    "illustration": "doorway-chest-stretch"
  },
  {
    "id": "lib-childs-pose",
    "name": "childsPose",
    "bodyPart": "Back",
    "description": "childsPoseDescription",
    "emoji": "🧗",
    "tracking": "duration",
    "illustration": "childs-pose"
  },
  {
    "id": "lib-kneeling-hip-flexor-stretch",
    "name": "kneelingHipFlexorStretch",
    "bodyPart": "Legs",
    "description": "kneelingHipFlexorStretchDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "kneeling-hip-flexor-stretch"
  },
  {
    "id": "lib-hamstring-stretch",
    "name": "hamstringStretch",
    "bodyPart": "Legs",
    "description": "hamstringStretchDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "hamstring-stretch"
  },
  {
    "id": "lib-standing-quad-stretch",
    "name": "standingQuadStretch",
    "bodyPart": "Legs",
    "description": "standingQuadStretchDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "standing-quad-stretch"
  },
  {
    "id": "lib-seated-forward-fold-stretch",
    "name": "seatedForwardFoldStretch",
    "bodyPart": "Legs",
    "description": "seatedForwardFoldStretchDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "seated-forward-fold-stretch"
  },
  {
    "id": "lib-cross-body-shoulder-stretch",
    "name": "crossBodyShoulderStretch",
    "bodyPart": "Shoulders",
    "description": "crossBodyShoulderStretchDescription",
    "emoji": "🤷",
    "tracking": "duration",
    "illustration": "cross-body-shoulder-stretch"
  },
  {
    "id": "lib-wall-calf-stretch",
    "name": "wallCalfStretch",
    "bodyPart": "Legs",
    "description": "wallCalfStretchDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "wall-calf-stretch"
  },
  {
    "id": "lib-butterfly-stretch",
    "name": "butterflyStretch",
    "bodyPart": "Legs",
    "description": "butterflyStretchDescription",
    "emoji": "🏃",
    "tracking": "duration",
    "illustration": "butterfly-stretch"
  }
];

/**
 * Ids that come from the catalogue rather than from the user.
 *
 * These are app content, like the built-in routines: they are not stored per
 * account, so there is nothing to delete. Editing one still works — the edit is
 * saved as an override and wins over the shipped copy.
 */
export const LIBRARY_EXERCISE_IDS: ReadonlySet<string> = new Set(
  LIBRARY_EXERCISES.map((exercise) => exercise.id),
);
