"use client";

import { useMemo } from "react";
import { useRouter } from "next/navigation";
import { ChevronLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import AuthGuard from "@/components/auth-guard";
import ExerciseIllustration from "@/components/exercise-illustration";
import { useLanguage } from "@/context/language-context";
import { useExercises } from "@/context/exercise-context";
import { ILLUSTRATIONS } from "@/lib/illustrations";

/**
 * Credit for the exercise artwork.
 *
 * CC BY-SA 4.0 requires the creator, a copyright and licence notice, a link to
 * the licence, and an indication of any changes. Without this screen the app is
 * not using the illustrations lawfully, which is why it is a route and not a
 * paragraph tucked into Settings.
 *
 * Everything here is read from `ILLUSTRATIONS`, generated by the import script
 * from the upstream manifest. Nothing is written by hand, so nothing goes stale
 * when the artwork is next re-imported.
 */
export default function LicensesPage() {
  const { t } = useLanguage();
  const { exercises } = useExercises();
  const router = useRouter();

  /** Only the 76 frames that derive from an earlier source name it. */
  const derived = useMemo(
    () =>
      Object.entries(ILLUSTRATIONS)
        .filter(([, meta]) => meta.upstream)
        .sort(([a], [b]) => a.localeCompare(b)),
    [],
  );

  const first = Object.values(ILLUSTRATIONS)[0];
  const nameFor = (slug: string) => {
    const match = exercises.find((exercise) => exercise.illustration === slug);
    return match ? t(match.name) : slug;
  };

  return (
    <AuthGuard>
      <div className="flex min-h-screen w-full flex-col overflow-y-auto bg-background">
        <main
          className="mx-auto w-full max-w-4xl flex-1 p-4 pb-24 md:p-6"
          style={{ paddingTop: "calc(1rem + env(safe-area-inset-top))" }}
        >
          <div className="mb-6 flex items-center gap-3">
            <Button
              variant="ghost"
              size="icon"
              onClick={() => router.back()}
              className="rounded-full"
              aria-label={t("goBack")}
            >
              <ChevronLeft className="h-6 w-6" />
            </Button>
            <h2 className="font-headline text-xl font-bold tracking-tight md:text-2xl">
              {t("licenses")}
            </h2>
          </div>

          <section className="glass-effect mb-6 rounded-xl border border-border/50 bg-card p-6 shadow-sm">
            <h3 className="mb-2 font-headline text-lg font-semibold">
              {t("illustrationCredit")}
            </h3>
            <p className="text-sm leading-relaxed text-muted-foreground">
              {t("illustrationCreditBody", {
                count: Object.keys(ILLUSTRATIONS).length,
                creator: first.creator,
              })}
            </p>
            <div className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-sm">
              <a
                href={first.creatorUrl}
                target="_blank"
                rel="noreferrer"
                className="text-primary underline"
              >
                {first.creator}
              </a>
              <a
                href={first.licenseUrl}
                target="_blank"
                rel="noreferrer"
                className="text-primary underline"
              >
                {first.license}
              </a>
              <a
                href="https://github.com/bryllim/workout-guide"
                target="_blank"
                rel="noreferrer"
                className="text-primary underline"
              >
                workout-guide
              </a>
            </div>
          </section>

          <section className="glass-effect mb-6 rounded-xl border border-border/50 bg-card p-6 shadow-sm">
            <h3 className="mb-1 font-headline text-lg font-semibold">
              {t("illustrationMetadata")}
            </h3>
            <p className="text-sm leading-relaxed text-muted-foreground">
              {t("illustrationMetadataBody")}
            </p>
          </section>

          <section className="glass-effect rounded-xl border border-border/50 bg-card p-6 shadow-sm">
            <h3 className="mb-1 font-headline text-lg font-semibold">
              {t("illustrationDerived")}
            </h3>
            <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
              {t("illustrationDerivedBody", { count: derived.length })}
            </p>

            <ul className="space-y-3">
              {derived.map(([slug, meta]) => (
                <li key={slug} className="flex items-start gap-3 border-t border-border/50 pt-3">
                  <ExerciseIllustration
                    exercise={{ illustration: slug }}
                    name={nameFor(slug)}
                    size="sm"
                  />
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-semibold">{nameFor(slug)}</p>
                    <p className="text-xs text-muted-foreground">{meta.upstream?.changes}</p>
                    <a
                      href={meta.upstream?.url}
                      target="_blank"
                      rel="noreferrer"
                      className="mt-0.5 inline-block break-all text-[11px] text-primary underline"
                    >
                      {meta.upstream?.name} · {meta.upstream?.license}
                    </a>
                  </div>
                </li>
              ))}
            </ul>
          </section>
        </main>
      </div>
    </AuthGuard>
  );
}
